# Generated by Django 6.0.4 on 2026-06-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_status_changed', 'Task Status Changed'), ('task_comment', 'Task Comment'), ('support_request_submitted', 'Support Request Submitted'), ('support_request_assigned', 'Support Request Assigned'), ('support_status_updated', 'Support Status Updated'), ('support_comment_added', 'Support Comment Added'), ('support_request_resolved', 'Support Request Resolved'), ('support_request_closed', 'Support Request Closed')], max_length=64),
        ),
    ]
