# Generated by Django 6.0.4 on 2026-08-12 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_line_manager'),
        ('organization', '0002_department_line_manager_unit_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='line_manager',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organization.team'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organization.unit'),
        ),
    ]
