# Generated by Django 6.0.4 on 2026-05-05 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_key', models.CharField(max_length=1024, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.taskactivity')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
