# Generated by Django 6.0.4 on 2026-05-11 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_recurrence_scheduled_for_recurringschedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recurringschedule',
            name='tasks_recur_is_acti_ad56ea_idx',
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='paused_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_schedules_paused', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recurringschedule',
            index=models.Index(fields=['is_active', 'is_paused', 'next_run_at'], name='tasks_recur_is_acti_2baf11_idx'),
        ),
    ]
