# Generated by Django 6.0.4 on 2026-05-18 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_recurringschedule_tasks_recur_is_acti_ad56ea_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary_data', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start_date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklySummaryShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries_shared', to=settings.AUTH_USER_MODEL)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='tasks.weeklysummary')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='weeklysummary',
            index=models.Index(fields=['user', '-week_start_date'], name='tasks_weekl_user_id_dbee06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklysummary',
            unique_together={('user', 'week_start_date')},
        ),
        migrations.AddIndex(
            model_name='weeklysummaryshare',
            index=models.Index(fields=['share_token'], name='tasks_weekl_share_t_adc160_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklysummaryshare',
            index=models.Index(fields=['shared_by', '-created_at'], name='tasks_weekl_shared__1b60a3_idx'),
        ),
    ]
