# Generated by Django 6.0.4 on 2026-05-20 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_phase2_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weeklysummaryusershare',
            name='unique_summary_shared_with',
        ),
        migrations.RemoveIndex(
            model_name='organizationsummarycache',
            name='tasks_organ_week_st_idx',
        ),
        migrations.RenameIndex(
            model_name='summaryexport',
            new_name='tasks_summa_exporte_96b931_idx',
            old_name='tasks_summa_experor_idx',
        ),
        migrations.RenameIndex(
            model_name='usergoal',
            new_name='tasks_userg_user_id_617423_idx',
            old_name='tasks_userg_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='weeklysummaryusershare',
            new_name='tasks_weekl_shared__5fbc89_idx',
            old_name='tasks_weekl_shared__idx',
        ),
        migrations.RenameIndex(
            model_name='weeklysummaryusershare',
            new_name='tasks_weekl_shared__085b4d_idx',
            old_name='tasks_weekl_shared_3f3b2_idx',
        ),
        migrations.AddField(
            model_name='weeklysummaryusershare',
            name='share_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='weeklysummaryusershare',
            unique_together={('summary', 'shared_with')},
        ),
    ]
