# Generated by Django 6.0.4 on 2026-05-26 10:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('tasks', '0007_remove_weeklysummaryusershare_unique_summary_shared_with_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryexport',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='metric',
            field=models.CharField(choices=[('tasks_completed', 'Tasks Completed'), ('high_priority_completed', 'High Priority Tasks Completed'), ('files_attached', 'Files Attached'), ('comments_added', 'Comments Added')], max_length=50),
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='organization.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReportSubreport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_report_subreports', to=settings.AUTH_USER_MODEL)),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subreports', to='tasks.dailyreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReportComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_report_comments', to=settings.AUTH_USER_MODEL)),
                ('subreport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.dailyreportsubreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['report_date', 'department'], name='tasks_daily_report__86f5f0_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['user', 'report_date'], name='tasks_daily_user_id_ed575b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('user', 'report_date')},
        ),
        migrations.AddIndex(
            model_name='dailyreportsubreport',
            index=models.Index(fields=['daily_report', 'created_at'], name='tasks_daily_daily_r_149586_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreportsubreport',
            index=models.Index(fields=['created_by', 'created_at'], name='tasks_daily_created_5c2eab_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreportcomment',
            index=models.Index(fields=['subreport', 'created_at'], name='tasks_daily_subrepo_eaf59b_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreportcomment',
            index=models.Index(fields=['author', 'created_at'], name='tasks_daily_author__170b8c_idx'),
        ),
    ]
