# Generated by Django 6.0.4 on 2026-09-01 12:21

import random
import string
from django.db import migrations, models

def generate_unique_codes(apps, schema_editor):
    InventoryItem = apps.get_model('inventory', 'InventoryItem')
    for item in InventoryItem.objects.filter(code__isnull=True):
        while True:
            code = ''.join(random.choices(string.digits, k=6))
            if not InventoryItem.objects.filter(code=code).exists():
                item.code = code
                item.save(update_fields=['code'])
                break

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorymaintenancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.RunPython(generate_unique_codes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='inventoryitem',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
