# Generated by Django 6.0.4 on 2026-09-01 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models

def migrate_attachments(apps, schema_editor):
    InventoryMaintenanceLog = apps.get_model('inventory', 'InventoryMaintenanceLog')
    MaintenanceLogAttachment = apps.get_model('inventory', 'MaintenanceLogAttachment')
    for log in InventoryMaintenanceLog.objects.exclude(attachment_url=''):
        MaintenanceLogAttachment.objects.create(
            log=log,
            object_key=log.attachment_url,
            file_name=log.attachment_url.split('/')[-1] if log.attachment_url else 'attachment',
            content_type='application/octet-stream',
            size=0
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLogAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_key', models.CharField(max_length=1024, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.inventorymaintenancelog')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(migrate_attachments, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='inventorymaintenancelog',
            name='attachment_url',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
