# Generated by Django 6.0.4 on 2026-09-23 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_inventorymaintenancelog_attachment_url_and_more'),
        ('organization', '0002_department_line_manager_unit_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryassignment',
            name='assigned_to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_assignment_history', to='organization.department'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='current_assignee_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inventory_items', to='organization.department'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='managing_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_inventory_items', to='organization.department'),
        ),
        migrations.AlterField(
            model_name='inventoryassignment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_assignment_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='inventoryassignment',
            index=models.Index(fields=['assigned_to_department', '-assigned_at'], name='inventory_i_assigne_6cc0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['current_assignee_department'], name='inventory_i_current_ee7cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['managing_department'], name='inventory_i_managin_42daaf_idx'),
        ),
    ]
