# Generated by Django 6.0.4 on 2026-09-23 12:24

from django.db import migrations


def set_managing_dept_it(apps, schema_editor):
    InventoryItem = apps.get_model('inventory', 'InventoryItem')
    Department = apps.get_model('organization', 'Department')

    # Get or create the IT department
    it_dept, _ = Department.objects.get_or_create(
        name='IT',
        defaults={'code': 'IT'}
    )

    # Bulk update all inventory items to have IT as the managing department
    items_to_update = InventoryItem.objects.exclude(managing_department=it_dept)
    items_to_update.update(managing_department=it_dept)

def reverse_migration(apps, schema_editor):
    InventoryItem = apps.get_model('inventory', 'InventoryItem')
    InventoryItem.objects.update(managing_department=None)

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryassignment_assigned_to_department_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_managing_dept_it, reverse_migration),
    ]
