# Generated by Django 6.0.4 on 2026-10-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='status_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'Maintenance'), ('retired', 'Retired'), ('unaccounted', 'Unaccounted')], default='available', max_length=20),
        ),
    ]
